#!/bin/sh
################################################################################
#
# File:    create-db-galcenter2
# Project: OpenSonATA
# Authors: The OpenSonATA code is the result of many programmers
#          over many years
#
# Copyright 2011 The SETI Institute
#
# OpenSonATA is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# OpenSonATA is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with OpenSonATA.  If not, see<http://www.gnu.org/licenses/>.
# 
# Implementers of this code are requested to include the caption
# "Licensed through SETI" with a link to setiQuest.org.
# 
# For alternate licensing arrangements, please contact
# The SETI Institute at www.seti.org or setiquest.org. 
#
################################################################################


# Create seeker database, and populate tables.

# Set these as needed:
dbhost="localhost"
dbname="sonata_obs_$1"

if [ "$dbhost" = "" ]
then
    echo "Must set dbhost in script"
    exit 1
fi

if [ "$dbname" = "" ]
then
    echo "Must set dbname in script"
    exit 1
fi

#set -x

# location of catalog data files

catalogDir="~/peter/catalogs/observing"

sourceFile()
{
    # Source the file, showing any warnings, but
    # ignoring any expected "note" messages (e.g., Unknown table)

    filename=$1
    mysql -h ${dbhost} ${dbname} --show-warnings -e \
      "set sql_notes=0; source ${filename};"
}

loadData()
{
    table=$1
    filename=$2

    nHeaderLines=2
    mysql --local-infile=1 -h ${dbhost} ${dbname} --show-warnings -e \
    "load data local infile '$filename' into table ${table}\
    fields terminated by ',' ignore $nHeaderLines lines;"
}

mysqladmin -h ${dbhost} --force drop ${dbname}
mysqladmin -h ${dbhost} create ${dbname}

echo "schema"
sourceFile sonata-obs.schema
